import { Course } from './types';

export const courses: Course[] = [
    // ===== COMPUTER SCIENCE & FUNDAMENTALS =====
    {
        id: 'cs50',
        title: 'CS50: Introduction to Computer Science',
        description: 'Harvard\'s legendary intro to CS. Learn C, Python, SQL, and web development through hands-on problem sets and a final project.',
        provider: 'Harvard University',
        platform: 'Harvard Online',
        thumbnail: 'https://images.unsplash.com/photo-1629904853716-f004b6b80635?w=800',
        duration: '12 weeks',
        level: 'Beginner',
        category: 'Computer Science',
        topics: ['C', 'Python', 'SQL', 'Algorithms', 'Data Structures'],
        skills: ['Problem Solving', 'Programming Fundamentals', 'Debugging'],
        rating: 4.9,
        views: '6M+',
        sourceUrl: 'https://cs50.harvard.edu/x/',
        isAudit: true,
        isFeatured: true,
        certificateType: 'paid',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'mit-6001x',
        title: 'Introduction to Computer Science and Programming Using Python',
        description: 'Learn to use computation to accomplish a variety of goals and solve complex problems using Python. MIT\'s foundational CS course via edX.',
        provider: 'MIT',
        platform: 'edX',
        thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800',
        duration: '9 weeks',
        level: 'Beginner',
        category: 'Computer Science',
        topics: ['Python', 'Computational Thinking', 'Algorithms'],
        rating: 4.8,
        views: '2M+',
        sourceUrl: 'https://www.edx.org/learn/computer-science/massachusetts-institute-of-technology-introduction-to-computer-science-and-programming-using-python',
        isAudit: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'algorithms-stanford',
        title: 'Algorithms Specialization',
        description: 'Learn the core algorithms that underlie modern computing. Covers divide-and-conquer, sorting, graph search, shortest paths, and NP-completeness.',
        provider: 'Stanford University',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800',
        duration: '4 months',
        level: 'Intermediate',
        category: 'Computer Science',
        topics: ['Algorithms', 'Graph Search', 'Dynamic Programming', 'Greedy Algorithms'],
        rating: 4.9,
        views: '1M+',
        sourceUrl: 'https://www.coursera.org/specializations/algorithms',
        isAudit: true,
        isFeatured: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'data-structures-ucsd',
        title: 'Data Structures and Algorithms',
        description: 'Master data structures and algorithmic techniques needed for technical interviews and competitive programming.',
        provider: 'UC San Diego',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
        duration: '8 months',
        level: 'Intermediate',
        category: 'Computer Science',
        topics: ['Data Structures', 'Algorithms', 'Graphs', 'Trees'],
        rating: 4.7,
        views: '500k',
        sourceUrl: 'https://www.coursera.org/specializations/data-structures-algorithms',
        isAudit: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== WEB DEVELOPMENT =====
    {
        id: 'freecodecamp-responsive',
        title: 'Responsive Web Design Certification',
        description: 'Earn a free verified certificate while learning HTML and CSS, including modern layout techniques like Flexbox and CSS Grid.',
        provider: 'freeCodeCamp',
        platform: 'freeCodeCamp',
        thumbnail: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800',
        duration: '300 hours',
        level: 'Beginner',
        category: 'Web Development',
        topics: ['HTML', 'CSS', 'Flexbox', 'Grid', 'Responsive Design'],
        rating: 4.8,
        views: '10M+',
        sourceUrl: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
        isAudit: false,
        isFeatured: true,
        certificateType: 'free',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'odin-project-foundations',
        title: 'The Odin Project — Foundations',
        description: 'A free, open-source curriculum covering everything you need to know to become a full-stack developer, starting from scratch.',
        provider: 'The Odin Project',
        platform: 'The Odin Project',
        thumbnail: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800',
        duration: '4-6 weeks',
        level: 'Beginner',
        category: 'Web Development',
        topics: ['HTML', 'CSS', 'JavaScript', 'Git', 'Command Line'],
        rating: 4.9,
        views: '500k+',
        sourceUrl: 'https://www.theodinproject.com/paths/foundations',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'fullstack-open',
        title: 'Full Stack Open',
        description: 'Deep dive into modern web development with React, Redux, Node.js, MongoDB, GraphQL, and TypeScript. Free certificate from University of Helsinki.',
        provider: 'University of Helsinki',
        platform: 'University Direct',
        thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
        duration: '14 weeks',
        level: 'Intermediate',
        category: 'Web Development',
        topics: ['React', 'Node.js', 'Express', 'MongoDB', 'GraphQL', 'TypeScript'],
        rating: 5.0,
        views: '200k+',
        sourceUrl: 'https://fullstackopen.com/en/',
        isAudit: false,
        isFeatured: true,
        certificateType: 'free',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'scrimba-react',
        title: 'Learn React for Free',
        description: 'Interactive React course covering components, props, state, hooks, and building real projects in Scrimba\'s unique coding environment.',
        provider: 'Scrimba',
        platform: 'Scrimba',
        thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
        duration: '12 hours',
        level: 'Beginner',
        category: 'Web Development',
        topics: ['React', 'JSX', 'Hooks', 'State Management'],
        rating: 4.9,
        views: '500k',
        sourceUrl: 'https://scrimba.com/learn/learnreact',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'javascript-info',
        title: 'The Modern JavaScript Tutorial',
        description: 'Comprehensive, free JavaScript guide from basics to advanced topics including DOM manipulation, async programming, and browser APIs.',
        provider: 'javascript.info',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800',
        duration: 'Self-paced',
        level: 'All Levels',
        category: 'Web Development',
        topics: ['JavaScript', 'DOM', 'Async', 'OOP', 'Browser APIs'],
        rating: 4.9,
        views: '5M+',
        sourceUrl: 'https://javascript.info/',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'you-dont-know-js',
        title: 'You Don\'t Know JS (Yet)',
        description: 'A series of books diving deep into the JavaScript language mechanics — scope, closures, types, coercion, and the prototype system.',
        provider: 'GitHub',
        platform: 'GitHub',
        thumbnail: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800',
        duration: 'Book Series',
        level: 'Advanced',
        category: 'Web Development',
        topics: ['JavaScript', 'Scope', 'Closures', 'Prototypes', 'Types'],
        rating: 4.9,
        views: '175k Stars',
        sourceUrl: 'https://github.com/getify/You-Dont-Know-JS',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'next-js-learn',
        title: 'Learn Next.js',
        description: 'Official interactive Next.js course by Vercel. Build a full-stack web app with the App Router, Tailwind CSS, and a Postgres database.',
        provider: 'Vercel',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=800',
        duration: '8 hours',
        level: 'Intermediate',
        category: 'Web Development',
        topics: ['Next.js', 'React', 'SSR', 'API Routes', 'Deployment'],
        rating: 4.8,
        views: '1M+',
        sourceUrl: 'https://nextjs.org/learn',
        isAudit: false,
        isNew: true,
        certificateType: 'none',
        addedDate: '2024-06-01',
        lastVerified: '2026-06-01',
    },

    // ===== AI & MACHINE LEARNING =====
    {
        id: 'ml-andrew-ng',
        title: 'Machine Learning Specialization',
        description: 'Andrew Ng\'s updated ML course covering supervised learning, unsupervised learning, and recommender systems with Python and NumPy.',
        provider: 'DeepLearning.AI',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=800',
        duration: '3 months',
        level: 'Intermediate',
        category: 'AI & Machine Learning',
        topics: ['Machine Learning', 'NumPy', 'Python', 'Regression', 'Neural Networks'],
        rating: 4.9,
        views: '4M+',
        sourceUrl: 'https://www.coursera.org/specializations/machine-learning-introduction',
        isAudit: true,
        isFeatured: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'fast-ai',
        title: 'Practical Deep Learning for Coders',
        description: 'Top-down approach to deep learning using PyTorch and fastai. Build state-of-the-art models for vision, NLP, and tabular data.',
        provider: 'fast.ai',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=800',
        duration: '7 weeks',
        level: 'Intermediate',
        category: 'AI & Machine Learning',
        topics: ['Deep Learning', 'PyTorch', 'Computer Vision', 'NLP'],
        rating: 4.9,
        views: '500k+',
        sourceUrl: 'https://course.fast.ai/',
        isAudit: false,
        isFeatured: true,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'deep-learning-specialization',
        title: 'Deep Learning Specialization',
        description: 'Master the fundamentals of deep learning with Andrew Ng. Build and train neural networks, CNNs, RNNs, and sequence models.',
        provider: 'DeepLearning.AI',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800',
        duration: '5 months',
        level: 'Intermediate',
        category: 'AI & Machine Learning',
        topics: ['Neural Networks', 'CNN', 'RNN', 'TensorFlow'],
        rating: 4.9,
        views: '1M+',
        sourceUrl: 'https://www.coursera.org/specializations/deep-learning',
        isAudit: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'huggingface-nlp',
        title: 'NLP Course',
        description: 'Learn to build NLP applications using the Hugging Face ecosystem — Transformers, Datasets, and Tokenizers. Work with BERT, GPT, and modern LLMs.',
        provider: 'Hugging Face',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
        duration: '40 hours',
        level: 'Intermediate',
        category: 'AI & Machine Learning',
        topics: ['NLP', 'Transformers', 'BERT', 'GPT', 'LLMs'],
        rating: 4.8,
        views: '300k+',
        sourceUrl: 'https://huggingface.co/learn/nlp-course',
        isAudit: false,
        isNew: true,
        certificateType: 'none',
        addedDate: '2024-06-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'google-ml-crash',
        title: 'Machine Learning Crash Course',
        description: 'Google\'s fast-paced, practical introduction to ML with TensorFlow. Covers linear regression, classification, and neural networks.',
        provider: 'Google',
        platform: 'Google Skillshop',
        thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
        duration: '15 hours',
        level: 'Beginner',
        category: 'AI & Machine Learning',
        topics: ['ML Fundamentals', 'TensorFlow', 'Feature Engineering'],
        rating: 4.7,
        views: '2M+',
        sourceUrl: 'https://developers.google.com/machine-learning/crash-course',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== DATA SCIENCE =====
    {
        id: 'python-for-everybody',
        title: 'Python for Everybody (PY4E)',
        description: 'Learn Python programming basics, data structures, web scraping, and database access through Dr. Chuck\'s beginner-friendly specialization.',
        provider: 'University of Michigan',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800',
        duration: '8 months',
        level: 'Beginner',
        category: 'Data Science',
        topics: ['Python', 'Data Structures', 'Web Scraping', 'Databases'],
        rating: 4.8,
        views: '5M+',
        sourceUrl: 'https://www.py4e.com/',
        isAudit: false,
        isFeatured: true,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'kaggle-intro-ml',
        title: 'Intro to Machine Learning',
        description: 'Learn the core ideas of ML and build your first models with scikit-learn. Covers decision trees, random forests, and model validation.',
        provider: 'Kaggle',
        platform: 'Kaggle',
        thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        duration: '3 hours',
        level: 'Beginner',
        category: 'Data Science',
        topics: ['Machine Learning', 'Scikit-learn', 'Model Validation'],
        rating: 4.7,
        views: '1M+',
        sourceUrl: 'https://www.kaggle.com/learn/intro-to-machine-learning',
        isAudit: false,
        certificateType: 'free',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'kaggle-pandas',
        title: 'Pandas Course',
        description: 'Solve real data analysis challenges with Pandas. Learn selecting, filtering, aggregating, and merging data in Python.',
        provider: 'Kaggle',
        platform: 'Kaggle',
        thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        duration: '4 hours',
        level: 'Beginner',
        category: 'Data Science',
        topics: ['Pandas', 'Data Manipulation', 'Data Cleaning'],
        rating: 4.8,
        views: '800k',
        sourceUrl: 'https://www.kaggle.com/learn/pandas',
        isAudit: false,
        certificateType: 'free',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'ibm-data-science',
        title: 'IBM Data Science Professional Certificate',
        description: 'Launch your career in data science. 10 courses covering data analysis, visualization, SQL, Python, machine learning, and a capstone project.',
        provider: 'IBM',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
        duration: '5 months',
        level: 'Beginner',
        category: 'Data Science',
        topics: ['Python', 'SQL', 'Data Visualization', 'Machine Learning'],
        rating: 4.6,
        views: '700k',
        sourceUrl: 'https://www.coursera.org/professional-certificates/ibm-data-science',
        isAudit: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== CLOUD COMPUTING =====
    {
        id: 'aws-practitioner',
        title: 'AWS Cloud Practitioner Essentials',
        description: 'Build your AWS Cloud knowledge foundation. Covers core AWS services, security, architecture, pricing, and support for the CLF-C02 exam.',
        provider: 'AWS',
        platform: 'AWS Skill Builder',
        thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
        duration: '6 hours',
        level: 'Beginner',
        category: 'Cloud Computing',
        topics: ['AWS', 'Cloud Fundamentals', 'EC2', 'S3', 'Security'],
        rating: 4.8,
        views: '3M+',
        sourceUrl: 'https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials',
        isAudit: false,
        isFeatured: true,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'gcp-fundamentals',
        title: 'Google Cloud Fundamentals: Core Infrastructure',
        description: 'Introduction to Google Cloud\'s core infrastructure products and services. Covers Compute Engine, Cloud Storage, VPCs, and Kubernetes.',
        provider: 'Google Cloud',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800',
        duration: '5 hours',
        level: 'Beginner',
        category: 'Cloud Computing',
        topics: ['GCP', 'Compute Engine', 'Cloud Storage', 'Kubernetes'],
        rating: 4.6,
        views: '500k',
        sourceUrl: 'https://www.coursera.org/learn/gcp-fundamentals',
        isAudit: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'azure-fundamentals',
        title: 'Azure Fundamentals (AZ-900)',
        description: 'Official Microsoft learning path for the AZ-900 exam. Covers cloud concepts, Azure services, security, privacy, and pricing. Earns a completion badge.',
        provider: 'Microsoft',
        platform: 'Microsoft Learn',
        thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800',
        duration: '10 hours',
        level: 'Beginner',
        category: 'Cloud Computing',
        topics: ['Azure', 'Cloud Concepts', 'Azure Services', 'Security'],
        rating: 4.7,
        views: '2M+',
        sourceUrl: 'https://learn.microsoft.com/en-us/training/paths/az-900-describe-cloud-concepts/',
        isAudit: false,
        certificateType: 'completion-badge',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== PROGRAMMING LANGUAGES =====
    {
        id: 'rust-microsoft',
        title: 'Take Your First Steps with Rust',
        description: 'Learn the Rust programming language from Microsoft. Covers ownership, borrowing, error handling, and building CLI tools.',
        provider: 'Microsoft',
        platform: 'Microsoft Learn',
        thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800',
        duration: '6 hours',
        level: 'Intermediate',
        category: 'Programming',
        topics: ['Rust', 'Memory Safety', 'Error Handling', 'Ownership'],
        rating: 4.8,
        views: '500k',
        sourceUrl: 'https://learn.microsoft.com/en-us/training/paths/rust-first-steps/',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'go-tour',
        title: 'A Tour of Go',
        description: 'Official interactive introduction to Go. Learn the language through exercises covering basics, methods, interfaces, and goroutines.',
        provider: 'Google',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1564865878688-9a244444042a?w=800',
        duration: '4 hours',
        level: 'Beginner',
        category: 'Programming',
        topics: ['Go', 'Concurrency', 'Goroutines', 'Interfaces'],
        rating: 4.7,
        views: '1M+',
        sourceUrl: 'https://go.dev/tour/',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'kotlin-bootcamp',
        title: 'Kotlin Bootcamp for Programmers',
        description: 'Learn Kotlin from Google engineers. Covers language basics, OOP, functional programming, and coroutines for Android development.',
        provider: 'Google',
        platform: 'Udacity',
        thumbnail: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=800',
        duration: '2 weeks',
        level: 'Intermediate',
        category: 'Programming',
        topics: ['Kotlin', 'Android', 'Coroutines', 'OOP'],
        rating: 4.6,
        views: '200k',
        sourceUrl: 'https://www.udacity.com/course/kotlin-bootcamp-for-programmers--ud9011',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== DESIGN =====
    {
        id: 'ux-design-google',
        title: 'Google UX Design Professional Certificate',
        description: 'Launch a career in UX design with Google. Learn user research, wireframing, prototyping in Figma, and portfolio building across 7 courses.',
        provider: 'Google',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1586717791821-3f44a5638d48?w=800',
        duration: '6 months',
        level: 'Beginner',
        category: 'Design',
        topics: ['UX', 'Figma', 'Wireframing', 'Prototyping', 'User Research'],
        rating: 4.8,
        views: '1M+',
        sourceUrl: 'https://www.coursera.org/professional-certificates/google-ux-design',
        isAudit: true,
        isFeatured: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'figma-basics',
        title: 'Figma: Design Basics',
        description: 'Official Figma resource library covering frames, auto layout, components, variables, and prototyping for UI designers.',
        provider: 'Figma',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800',
        duration: '4 hours',
        level: 'Beginner',
        category: 'Design',
        topics: ['Figma', 'UI Design', 'Components', 'Auto Layout'],
        rating: 4.9,
        views: '800k',
        sourceUrl: 'https://www.figma.com/resource-library/design-basics/',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== DEVOPS =====
    {
        id: 'docker-getting-started',
        title: 'Docker Getting Started',
        description: 'Official Docker tutorial covering containerization fundamentals, images, volumes, networking, and Docker Compose multi-container apps.',
        provider: 'Docker',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800',
        duration: '2 hours',
        level: 'Beginner',
        category: 'DevOps',
        topics: ['Docker', 'Containers', 'Images', 'Docker Compose'],
        rating: 4.7,
        views: '2M+',
        sourceUrl: 'https://docs.docker.com/get-started/',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'kubernetes-basics',
        title: 'Kubernetes Basics',
        description: 'Official interactive Kubernetes tutorial. Learn to deploy, scale, and update containerized applications on a Kubernetes cluster.',
        provider: 'Kubernetes',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800',
        duration: '3 hours',
        level: 'Intermediate',
        category: 'DevOps',
        topics: ['Kubernetes', 'Pods', 'Deployments', 'Services'],
        rating: 4.6,
        views: '500k',
        sourceUrl: 'https://kubernetes.io/docs/tutorials/kubernetes-basics/',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'git-github',
        title: 'Git and GitHub for Beginners',
        description: 'Complete Git and GitHub crash course by freeCodeCamp. Learn version control, branching, pull requests, and collaborative workflows.',
        provider: 'freeCodeCamp',
        platform: 'YouTube',
        thumbnail: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800',
        duration: '1 hour',
        level: 'Beginner',
        category: 'DevOps',
        topics: ['Git', 'GitHub', 'Version Control', 'Branching'],
        rating: 4.9,
        views: '3M+',
        sourceUrl: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== DATABASE =====
    {
        id: 'sql-khan',
        title: 'Intro to SQL',
        description: 'Learn SQL fundamentals with Khan Academy\'s interactive exercises. Covers queries, joins, aggregations, and database design.',
        provider: 'Khan Academy',
        platform: 'Khan Academy',
        thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800',
        duration: '3 hours',
        level: 'Beginner',
        category: 'Database',
        topics: ['SQL', 'Queries', 'Joins', 'Aggregations'],
        rating: 4.8,
        views: '2M+',
        sourceUrl: 'https://www.khanacademy.org/computing/computer-programming/sql',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'mongodb-university',
        title: 'MongoDB Basics (M001)',
        description: 'Learn to work with MongoDB — the most popular NoSQL database. Covers CRUD operations, querying, aggregation, and indexing with a free certificate.',
        provider: 'MongoDB',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800',
        duration: '4 weeks',
        level: 'Beginner',
        category: 'Database',
        topics: ['MongoDB', 'NoSQL', 'CRUD', 'Aggregation'],
        rating: 4.7,
        views: '500k',
        sourceUrl: 'https://learn.mongodb.com/courses/m001-mongodb-basics',
        isAudit: false,
        certificateType: 'free',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== CYBERSECURITY =====
    {
        id: 'google-cybersecurity',
        title: 'Google Cybersecurity Professional Certificate',
        description: 'Prepare for a career in cybersecurity in under 6 months. Covers security operations, Linux, Python scripting, SIEM tools, and incident response.',
        provider: 'Google',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
        duration: '6 months',
        level: 'Beginner',
        category: 'Cybersecurity',
        topics: ['Security', 'Linux', 'Python', 'SIEM', 'Incident Response'],
        rating: 4.8,
        views: '500k',
        sourceUrl: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
        isAudit: true,
        isNew: true,
        certificateType: 'audit-only',
        addedDate: '2024-06-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'tryhackme-intro',
        title: 'Introduction to Cyber Security',
        description: 'Hands-on introduction to cybersecurity with TryHackMe\'s learning path. Covers offensive security, defensive security, and web application hacking.',
        provider: 'TryHackMe',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
        duration: '24 hours',
        level: 'Beginner',
        category: 'Cybersecurity',
        topics: ['Cyber Security', 'Ethical Hacking', 'Web Security'],
        rating: 4.8,
        views: '1M+',
        sourceUrl: 'https://tryhackme.com/path/outline/introtocyber',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== SOFTWARE ENGINEERING =====
    {
        id: 'system-design-primer',
        title: 'The System Design Primer',
        description: 'Comprehensive open-source guide to system design interviews. Learn how to design large-scale systems like Twitter, Dropbox, and YouTube.',
        provider: 'GitHub',
        platform: 'GitHub',
        thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
        duration: 'Self-paced',
        level: 'Advanced',
        category: 'Software Engineering',
        topics: ['System Design', 'Scalability', 'Architecture', 'Databases'],
        rating: 4.9,
        views: '260k Stars',
        sourceUrl: 'https://github.com/donnemartin/system-design-primer',
        isAudit: false,
        isFeatured: true,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'clean-code',
        title: 'Clean Code Fundamentals',
        description: 'Learn how to write clean, maintainable code through SOLID principles, design patterns, and refactoring techniques from this freeCodeCamp video.',
        provider: 'YouTube',
        platform: 'YouTube',
        thumbnail: 'https://images.unsplash.com/photo-1522542550221-31fd8575f5a4?w=800',
        duration: '4 hours',
        level: 'Intermediate',
        category: 'Software Engineering',
        topics: ['Clean Code', 'SOLID', 'Design Patterns', 'Refactoring'],
        rating: 4.7,
        views: '500k',
        sourceUrl: 'https://www.youtube.com/watch?v=7EmboKQH8lM',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== MOBILE DEVELOPMENT =====
    {
        id: 'flutter-codelabs',
        title: 'Flutter Codelabs',
        description: 'Official Google codelabs for Flutter development. Build cross-platform mobile apps with Dart, covering navigation, state management, and UI.',
        provider: 'Google',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
        duration: '10 hours',
        level: 'Beginner',
        category: 'Mobile Development',
        topics: ['Flutter', 'Dart', 'Cross-Platform', 'Widgets'],
        rating: 4.7,
        views: '800k',
        sourceUrl: 'https://docs.flutter.dev/codelabs',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'android-basics-kotlin',
        title: 'Android Basics with Compose',
        description: 'Official Google course for building Android apps with Jetpack Compose and Kotlin. No experience needed — covers UI, navigation, data, and networking.',
        provider: 'Google',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=800',
        duration: '8 units',
        level: 'Beginner',
        category: 'Mobile Development',
        topics: ['Android', 'Kotlin', 'Jetpack Compose', 'Material Design'],
        rating: 4.8,
        views: '1M+',
        sourceUrl: 'https://developer.android.com/courses/android-basics-compose/course',
        isAudit: false,
        isNew: true,
        certificateType: 'none',
        addedDate: '2024-06-01',
        lastVerified: '2026-06-01',
    },

    // ===== BLOCKCHAIN =====
    {
        id: 'blockchain-berkeley',
        title: 'Blockchain Fundamentals',
        description: 'UC Berkeley\'s introduction to blockchain technology. Covers Bitcoin, Ethereum, cryptographic primitives, and consensus mechanisms.',
        provider: 'UC Berkeley',
        platform: 'edX',
        thumbnail: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
        duration: '4 weeks',
        level: 'Beginner',
        category: 'Blockchain',
        topics: ['Blockchain', 'Bitcoin', 'Cryptography', 'Consensus'],
        rating: 4.6,
        views: '200k',
        sourceUrl: 'https://www.edx.org/learn/blockchain/university-of-california-berkeley-blockchain-fundamentals',
        isAudit: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'solidity-crypto-zombies',
        title: 'CryptoZombies',
        description: 'Learn to code Ethereum DApps by building your own crypto-collectibles game. Covers Solidity, smart contracts, and Web3 interaction.',
        provider: 'Loom Network',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
        duration: '8 hours',
        level: 'Beginner',
        category: 'Blockchain',
        topics: ['Solidity', 'Ethereum', 'Smart Contracts', 'Web3'],
        rating: 4.8,
        views: '500k+',
        sourceUrl: 'https://cryptozombies.io/',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== MATHEMATICS =====
    {
        id: 'khan-linear-algebra',
        title: 'Linear Algebra',
        description: 'Comprehensive linear algebra course from Khan Academy. Covers vectors, matrices, linear transformations, eigenvalues, and eigenvectors.',
        provider: 'Khan Academy',
        platform: 'Khan Academy',
        thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800',
        duration: '20 hours',
        level: 'Intermediate',
        category: 'Mathematics',
        topics: ['Linear Algebra', 'Vectors', 'Matrices', 'Eigenvalues'],
        rating: 4.8,
        views: '5M+',
        sourceUrl: 'https://www.khanacademy.org/math/linear-algebra',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'mit-calculus',
        title: 'Single Variable Calculus',
        description: 'MIT\'s full single-variable calculus course with lecture videos, problem sets, and exams. Covers limits, derivatives, integrals, and series.',
        provider: 'MIT',
        platform: 'MIT OpenCourseWare',
        thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800',
        duration: '40 hours',
        level: 'Intermediate',
        category: 'Mathematics',
        topics: ['Calculus', 'Derivatives', 'Integrals', 'Series'],
        rating: 4.9,
        views: '3M+',
        sourceUrl: 'https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/',
        isAudit: false,
        certificateType: 'none',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },

    // ===== BUSINESS =====
    {
        id: 'google-pm',
        title: 'Google Project Management Certificate',
        description: 'Learn project management methodology including Agile, Scrum, and traditional approaches from Google. Prepares you for entry-level PM roles.',
        provider: 'Google',
        platform: 'Coursera',
        thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
        duration: '6 months',
        level: 'Beginner',
        category: 'Business',
        topics: ['Project Management', 'Agile', 'Scrum', 'Leadership'],
        rating: 4.8,
        views: '1M+',
        sourceUrl: 'https://www.coursera.org/professional-certificates/google-project-management',
        isAudit: true,
        certificateType: 'audit-only',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    },
    {
        id: 'yc-startup-school',
        title: 'Startup School',
        description: 'Y Combinator\'s free online program for founders. Learn how to build a startup — idea validation, product-market fit, fundraising, and growth.',
        provider: 'Y Combinator',
        platform: 'Other',
        thumbnail: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800',
        duration: '8 weeks',
        level: 'All Levels',
        category: 'Business',
        topics: ['Startups', 'Fundraising', 'Product', 'Growth'],
        rating: 4.9,
        views: '500k+',
        sourceUrl: 'https://www.startupschool.org/',
        isAudit: false,
        certificateType: 'free',
        addedDate: '2024-01-01',
        lastVerified: '2026-06-01',
    }
];

// Derived data
export const courseCategories = Array.from(new Set(courses.map(c => c.category)));
export const courseTopics = Array.from(new Set(courses.flatMap(c => c.topics)));
export const coursePlatforms = Array.from(new Set(courses.map(c => c.platform).filter(Boolean)));
export const featuredCourses = courses.filter(c => c.isFeatured);
export const newCourses = courses.filter(c => c.isNew);

// Resources (keeping existing)
export const resources = [
    { id: 'roadmap-sh', title: 'roadmap.sh', type: 'Roadmap', description: 'Community driven roadmaps for developers.', url: 'https://roadmap.sh', tags: ['Career', 'Guidance'] },
    { id: 'freecodecamp', title: 'freeCodeCamp', type: 'Platform', description: 'Learn to code for free. Build projects.', url: 'https://www.freecodecamp.org', tags: ['Coding', 'Practice'] },
    { id: 'mdn', title: 'MDN Web Docs', type: 'Documentation', description: 'Official web standards documentation.', url: 'https://developer.mozilla.org', tags: ['Web Dev', 'Reference'] },
    { id: 'leetcode', title: 'LeetCode', type: 'Practice', description: 'Coding interview preparation platform.', url: 'https://leetcode.com', tags: ['Interview', 'Algorithms'] },
    { id: 'mit-ocw', title: 'MIT OpenCourseWare', type: 'Education', description: 'MIT course materials online for free.', url: 'https://ocw.mit.edu', tags: ['University', 'Deep Dive'] },
    { id: 'kaggle', title: 'Kaggle', type: 'Practice', description: 'Data science competitions and datasets.', url: 'https://kaggle.com', tags: ['Data Science', 'ML'] }
];
